#!/usr/bin/env python3
"""
Generate VM/src/llprim_set_primitive_params.inl from lsl_definitions.yaml.

Should be run if new prim params are added.
"""

from __future__ import annotations

import os.path
import sys


REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
LSL_DEFS_PKG = os.path.join(
    REPO_ROOT, "stage", "packages", "lsl_definitions", "python"
)
LSL_DEFS_YAML = os.path.join(
    REPO_ROOT, "stage", "packages", "lsl_definitions", "lsl_definitions.yaml"
)
OUTPUT_PATH = os.path.join(REPO_ROOT, "VM", "src", "llprim_set_primitive_params.inl")

sys.path.insert(0, LSL_DEFS_PKG)

from lsl_definitions import LSLDefinitionParser  # noqa: E402
from lsl_definitions.rulesets import expand_spp_builder  # noqa: E402
from lsl_definitions.utils import write_if_different  # noqa: E402


SEMANTIC = {
    "integer": "i",
    # `link` may only be a tagged integer at runtime, currently.
    "link":    "i",
    "float":   "f",
    "string":  "s",
    "vector":  "v",
    "rotation":"r",
    "boolean": "b",
    "asset":   "a",
}


def semantic_for(method) -> str:
    sem = ""
    if method.face_target:
        sem += "i"
    if method.nullable:
        sem += "?"
    for p in method.params:
        if p.type.name not in SEMANTIC:
            raise ValueError(f"unknown param type {p.type.name!r} on {method.name!r}")
        sem += SEMANTIC[p.type.name]
    return sem


def render(spec) -> str:
    lines = [
        "// AUTO-GENERATED by tools/gen_primparams_methods.py, do not edit",
        "// Derived from lsl_definitions.yaml",
        "",
        "static const PrimParamsSetterMethod SET_PRIMITIVE_PARAMS_METHODS[] = {",
    ]
    for m in spec.methods:
        sem = semantic_for(m)
        variant = m.variant_tag if m.variant_tag is not None else -1
        comment = m.rule_name
        if m.variant_tag is not None:
            comment = f"{m.rule_name} + variant {m.variant_tag}"
        lines.append(
            f'    {{ "{m.name}", "{sem}", {m.rule_tag}, {variant} }}, // {comment}'
        )
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> int:
    lsl = LSLDefinitionParser().parse_file(LSL_DEFS_YAML)
    spec = expand_spp_builder(lsl)
    if not spec.methods:
        print("no methods produced", file=sys.stderr)
        return 1
    write_if_different(OUTPUT_PATH, render(spec))
    print(f"wrote {len(spec.methods)} methods to {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
